### ISSUE TITLE
Very Minor Multiplayer Compat Issue

### ISSUE THREAD

**Issue by Shrakna** [emipa606/Aquarium#2]
Recently someone reported this mod in the MP Discord. It states it comes with native MP support which is very true. However "Aquarium decorations do not sync, but this does not cause a desync." Therefore this mod will be rated a 3 in terms of compatibility instead of a 4 (perfect).  

Again it causes no issues as it's just visual, but figured I'd just slide it over here for the sake of documenting it. 

MP Discord report:
https://discord.com/channels/524286515644203028/698315657833611354/817822918100779039

**Comment by emipa606** [comment]
The link does not work for me, I assume there is a discord-server I need to join first?
Is there a suggested solution for the issue?

**Comment by Shrakna** [comment]
Oh yeah apologies. The MP Discord is: https://discord.gg/S4bxXpv

You'd need to join and press the green checkbox halfway down the FAQ to access the Dev Chat. 

I don't really know a suggested solution as I don't know anything about coding, but there is a Multiplayer API which I assume pelador used initially to provide the native compat support, but the visualization just was never synced itself. 

Again its a very minor thing, but the modders in the Dev Chat would probably have some sort of idea on how to fix it. I just figured here might be somewhere to bring it up since it was a native compat.

**Comment by emipa606** [comment]
Should be fixed with the latest release
